# Generated by Django 3.1.7 on 2021-03-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=10, verbose_name='作家')),
                ('brief', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'db_table': 'django_author',
            },
        ),
        migrations.CreateModel(
            name='BooksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=32, verbose_name='书名')),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'django_books',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=2, verbose_name='字母')),
            ],
            options={
                'verbose_name': '字母',
                'verbose_name_plural': '字母',
                'db_table': 'django_mark',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, verbose_name='账号')),
                ('passwd', models.CharField(max_length=32, verbose_name='密码')),
                ('gmail', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'django_users',
            },
        ),
        migrations.CreateModel(
            name='Roleinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_class', models.CharField(choices=[('dps', 'DPS'), ('tank', 'TANK'), ('healer', 'healer')], default='dps', max_length=10, verbose_name='职业')),
                ('role_gender', models.CharField(choices=[('gentleman', 'gentleman'), ('madam', 'madam')], default='gentleman', max_length=10, verbose_name='性别')),
                ('role_name', models.CharField(max_length=10, verbose_name='角色名')),
                ('role_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DragonOathApp.userinfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'django_roles',
            },
        ),
        migrations.CreateModel(
            name='Pageview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.IntegerField(blank=True, null=True, verbose_name='阅读量')),
                ('comments', models.IntegerField(blank=True, null=True, verbose_name='评论数')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DragonOathApp.booksinfo', verbose_name='书籍')),
            ],
            options={
                'verbose_name': '阅读量',
                'verbose_name_plural': '阅读量',
                'db_table': 'django_pageview',
            },
        ),
        migrations.CreateModel(
            name='Holmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=32, verbose_name='书名')),
                ('content', models.TextField(verbose_name='内容')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DragonOathApp.booksinfo', verbose_name='书籍ID')),
            ],
            options={
                'verbose_name': '福尔摩斯',
                'verbose_name_plural': '福尔摩斯',
                'db_table': 'django_holmes',
            },
        ),
        migrations.CreateModel(
            name='ForeignAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('brief', models.TextField(verbose_name='简介')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DragonOathApp.mark', verbose_name='字母')),
            ],
        ),
    ]
